---
name: midterm
break: true
indent: 4
---

src/main/java/midterm:
    WidgetBill.java:
        ConfirmFileExists
        CountSingleLineComments --language Java --count 4
        MatchFileFragment --fragment "{Your Name Here}" --count 0 --exact
        MatchFileFragment --fragment "TODO" --count 0 --exactt

src/main/java/midterm:
    Widget.java:
        ConfirmFileExists
        
ExecuteCommand --command "gradle build"
ExecuteCommand --command "gradle -q --console plain interactiveGradeRun"
CountCommandOutput --command "gradle -q --console plain interactiveGradeRun" --count 11 --exact
MatchCommandFragment --command "gradle -q --console plain interactiveGradeRun" --fragment "150.6" --count 1 --exact
MatchCommandFragment --command "gradle -q --console plain interactiveGradeRun" --fragment "184.8" --count 1 --exact
MatchCommandFragment --command "gradle -q --console plain interactiveGradeRun" --fragment "76.5" --count 1 --exact
MatchCommandFragment --command "gradle -q --console plain interactiveGradeRun" --fragment "227.2" --count 1 --exact